In [2]:
import numpy as np

In [5]:
arr = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [6]:
arr.shape

(2, 4)

In [7]:
arr[0,0]

0

In [8]:
arr[1,3]

7

In [9]:
arr[0]

array([0, 1, 2, 3])

In [10]:
arr[0,3] = 10
arr

array([[ 0,  1,  2, 10],
       [ 4,  5,  6,  7]])

In [12]:
vec = np.array([3,5])
vec

array([3, 5])